# permissions for end users to view helloapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: helloapp-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: hellooperator
    app.kubernetes.io/part-of: hellooperator
    app.kubernetes.io/managed-by: kustomize
  name: helloapp-viewer-role
rules:
- apiGroups:
  - apps.zsh.io
  resources:
  - helloapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.zsh.io
  resources:
  - helloapps/status
  verbs:
  - get
