apiVersion: apps.zsh.io/v1
kind: HelloApp
metadata:
  labels:
    label: helloapp-v2
    app.kubernetes.io/name: helloapp
    app.kubernetes.io/instance: helloapp-v2
    app.kubernetes.io/part-of: hellooperator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: hellooperator
  name: helloapp-v2
spec:
  # 新增下述内容
  replicas: 3 # 设置副本数
  label: helloapp-v2
  template: # 按照 pod 模板设置 pod 规格
    spec:
      containers:
        - image:  nginx
          name:  app
